export const CONSTANTS = {
  SKILL_MISMATCH: "SKILL_MISMATCH",
  NOT_CERTIFIED: "NOT_CERTIFIED",
  DOUBLE_BOOKING: "DOUBLE_BOOKING",
  MIN_REST_VIOLATION: "MIN_REST_VIOLATION",
  DAILY_LIMIT_EXCEEDED: "DAILY_LIMIT_EXCEEDED",
  DAILY_OVERTIME_WARNING: "DAILY_OVERTIME_WARNING",
  WEEKLY_OVERTIME_WARNING: "WEEKLY_OVERTIME_WARNING",
  HEADCOUNT_REACHED: "HEADCOUNT_REACHED",
};
