import { Dashboard } from "@src/layout";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "ShiftSync — Multi-Location Staff Scheduling Platform",
  description: "Generated by create next app",
};

export default function Home() {
  return <Dashboard />;
}
